# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {
  thunderforest_api_key: '{{ env.THUNDERFOREST_API_KEY }}', # Doesn't work as of 7/21/25
  # wego_stop_id: HERLINWF,
  wego_stop_id: PORGRESF,
  # wego_stop_id: GXOGREEN,
  # wego_stop_id: MCC4_14,
}

# override variables
variables:
  trmnl: {
    user: {
      locale: "en",
      time_zone: Central Time (US & Canada),
      time_zone_iana: America/Chicago,
      utc_offset: -21600
    },
    plugin_settings: {
      instance_name: 'WeGo Public Transit'
    }
  }
